-- E94-S01: P2 Library — imported_courses, imported_videos, imported_pdfs, authors, books
-- + upsert_book_progress() SECURITY DEFINER function.
--
-- This migration adds all P2 content-library tables to the Supabase schema. It
-- is the prerequisite for all downstream E94 sync wiring stories (S02–S07).
--
-- Timestamp note: filename 20260413 reflects the design date; story was authored
-- 2026-04-19. The earlier timestamp is intentional — it orders immediately after
-- 20260413000002_p1_learning_content.sql and before the P0 fixup migrations.
-- Do NOT edit this file post-commit; fixups live in separate migrations.
--
-- Dependency order (all P2 tables are independent of each other; all depend on P0):
--   1. imported_courses
--   2. imported_videos
--   3. imported_pdfs
--   4. authors
--   5. books
--   6. upsert_book_progress() function (depends on books table)
--
-- Key non-obvious invariants:
--   - imported_videos."order" must be double-quoted in DDL (SQL reserved word)
--   - books.source is decomposed into source_type + source_url (FileSystemFileHandle
--     is non-serializable; 'fileHandle' variant excluded from source_type CHECK)
--   - books.progress is REAL 0–100 (not 0–1) per types.ts line 774
--   - upsert_book_progress() is UPDATE-only; book row must pre-exist via syncableWrite
--   - moddatetime extension is already installed by P0 — NOT re-created here
--   - Trigger names use {tablename}_set_updated_at prefix to avoid cross-table collisions
--   - thumbnail_url (imported_courses) and file_url (imported_pdfs) are NULL placeholders
--     until E94-S04 wires Storage upload
--
-- Idempotency: all statements use IF NOT EXISTS / CREATE OR REPLACE /
-- DROP POLICY IF EXISTS / DROP TRIGGER IF EXISTS. Safe to re-run.
-- Rollback: supabase/migrations/rollback/20260413000003_p2_library_rollback.sql

BEGIN;


-- ─── Unit 1: imported_courses ────────────────────────────────────────────────
-- User-imported course collections (YouTube playlists, local directories, etc.)
-- status CHECK uses hyphenated values matching LearnerCourseStatus from types.ts.
-- author_id is TEXT (not UUID FK) — matches ImportedAuthor.id: string in Dexie.
-- thumbnail_url is NULL by default; populated by E94-S04 Storage wiring.
-- youtube_* columns support YouTube playlist import flow.
CREATE TABLE IF NOT EXISTS public.imported_courses (
  id                     UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id                UUID         NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name                   TEXT         NOT NULL,
  description            TEXT,
  imported_at            TIMESTAMPTZ  NOT NULL,
  category               TEXT         NOT NULL DEFAULT '',
  tags                   TEXT[]       NOT NULL DEFAULT '{}',
  status                 TEXT         NOT NULL DEFAULT 'not-started'
                           CHECK (status IN ('not-started', 'active', 'completed', 'paused')),
  video_count            INT          NOT NULL DEFAULT 0,
  pdf_count              INT          NOT NULL DEFAULT 0,
  total_duration         FLOAT,
  total_file_size        BIGINT,
  max_resolution_height  INT,
  source                 TEXT         DEFAULT 'local',
  youtube_playlist_id    TEXT,
  youtube_channel_id     TEXT,
  youtube_channel_title  TEXT,
  youtube_thumbnail_url  TEXT,
  youtube_published_at   TIMESTAMPTZ,
  last_refreshed_at      TIMESTAMPTZ,
  author_id              TEXT,
  thumbnail_url          TEXT,
  created_at             TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at             TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- Incremental download cursor for E92-S06.
CREATE INDEX IF NOT EXISTS idx_imported_courses_user_updated
  ON public.imported_courses (user_id, updated_at);

ALTER TABLE public.imported_courses ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "users_own_data" ON public.imported_courses;
CREATE POLICY "users_own_data"
  ON public.imported_courses
  FOR ALL
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- Auto-update updated_at on every UPDATE (LWW sync tables use server-assigned timestamp).
-- Trigger name prefixed with tablename to avoid cross-table name collisions.
DROP TRIGGER IF EXISTS imported_courses_set_updated_at ON public.imported_courses;
CREATE TRIGGER imported_courses_set_updated_at
  BEFORE UPDATE ON public.imported_courses
  FOR EACH ROW EXECUTE FUNCTION extensions.moddatetime('updated_at');


-- ─── Unit 2: imported_videos ─────────────────────────────────────────────────
-- Videos within an imported course. "order" is double-quoted — SQL reserved word.
-- course_id is TEXT (no FK to imported_courses — consistent with content_progress pattern).
-- chapters JSONB stores Chapter[] from YouTube chapter auto-detection.
-- Two indexes: user_updated (sync cursor) + course (per-course video listing).
CREATE TABLE IF NOT EXISTS public.imported_videos (
  id                    UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id               UUID         NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  course_id             TEXT         NOT NULL,
  filename              TEXT         NOT NULL DEFAULT '',
  path                  TEXT         NOT NULL DEFAULT '',
  duration              FLOAT        NOT NULL DEFAULT 0,
  format                TEXT         NOT NULL DEFAULT 'mp4',
  "order"               INT          NOT NULL DEFAULT 0,
  file_size             BIGINT,
  width                 INT,
  height                INT,
  youtube_video_id      TEXT,
  youtube_url           TEXT,
  thumbnail_url         TEXT,
  description           TEXT,
  chapters              JSONB,
  removed_from_youtube  BOOLEAN      NOT NULL DEFAULT FALSE,
  created_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at            TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- Incremental download cursor for E92-S06.
CREATE INDEX IF NOT EXISTS idx_imported_videos_user_updated
  ON public.imported_videos (user_id, updated_at);

-- Per-course video listing (used by course detail view and sync filtering).
CREATE INDEX IF NOT EXISTS idx_imported_videos_course
  ON public.imported_videos (user_id, course_id);

ALTER TABLE public.imported_videos ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "users_own_data" ON public.imported_videos;
CREATE POLICY "users_own_data"
  ON public.imported_videos
  FOR ALL
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP TRIGGER IF EXISTS imported_videos_set_updated_at ON public.imported_videos;
CREATE TRIGGER imported_videos_set_updated_at
  BEFORE UPDATE ON public.imported_videos
  FOR EACH ROW EXECUTE FUNCTION extensions.moddatetime('updated_at');


-- ─── Unit 3: imported_pdfs ───────────────────────────────────────────────────
-- PDF documents within an imported course.
-- file_url is NULL until E94-S04 wires Storage upload (same pattern as thumbnail_url).
-- course_id is TEXT (no FK — consistent with imported_videos.course_id).
CREATE TABLE IF NOT EXISTS public.imported_pdfs (
  id          UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID         NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  course_id   TEXT         NOT NULL,
  filename    TEXT         NOT NULL DEFAULT '',
  path        TEXT         NOT NULL DEFAULT '',
  page_count  INT          NOT NULL DEFAULT 0,
  file_url    TEXT,
  created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- Incremental download cursor for E92-S06.
CREATE INDEX IF NOT EXISTS idx_imported_pdfs_user_updated
  ON public.imported_pdfs (user_id, updated_at);

ALTER TABLE public.imported_pdfs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "users_own_data" ON public.imported_pdfs;
CREATE POLICY "users_own_data"
  ON public.imported_pdfs
  FOR ALL
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP TRIGGER IF EXISTS imported_pdfs_set_updated_at ON public.imported_pdfs;
CREATE TRIGGER imported_pdfs_set_updated_at
  BEFORE UPDATE ON public.imported_pdfs
  FOR EACH ROW EXECUTE FUNCTION extensions.moddatetime('updated_at');


-- ─── Unit 4: authors ─────────────────────────────────────────────────────────
-- User-managed author profiles (ImportedAuthor, not the static pre-seeded Author type).
-- course_ids TEXT[] matches ImportedAuthor.courseIds: string[] in types.ts.
-- social_links JSONB: schema-flexible for { website?, twitter?, linkedin? } structure.
-- is_preseeded flags rows migrated from the static pre-seeded catalog.
CREATE TABLE IF NOT EXISTS public.authors (
  id                UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id           UUID         NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name              TEXT         NOT NULL,
  title             TEXT,
  bio               TEXT,
  short_bio         TEXT,
  photo_url         TEXT,
  course_ids        TEXT[]       NOT NULL DEFAULT '{}',
  specialties       TEXT[],
  years_experience  INT,
  education         TEXT,
  social_links      JSONB,
  featured_quote    TEXT,
  is_preseeded      BOOLEAN      NOT NULL DEFAULT FALSE,
  created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- Incremental download cursor for E92-S06.
CREATE INDEX IF NOT EXISTS idx_authors_user_updated
  ON public.authors (user_id, updated_at);

ALTER TABLE public.authors ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "users_own_data" ON public.authors;
CREATE POLICY "users_own_data"
  ON public.authors
  FOR ALL
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP TRIGGER IF EXISTS authors_set_updated_at ON public.authors;
CREATE TRIGGER authors_set_updated_at
  BEFORE UPDATE ON public.authors
  FOR EACH ROW EXECUTE FUNCTION extensions.moddatetime('updated_at');


-- ─── Unit 5: books ───────────────────────────────────────────────────────────
-- User book library. Book.source (ContentSource union) is decomposed into
-- source_type + source_url to avoid serializing non-serializable FileSystemFileHandle.
-- 'fileHandle' variant is intentionally excluded from source_type CHECK —
-- syncableWrite strips it in E94-S02 before upload.
-- progress is REAL 0–100 (NOT 0–1) per types.ts line 774.
-- status CHECK matches BookStatus from types.ts line 686.
-- chapters and current_position stored as JSONB (BookChapter[] and ContentPosition).
-- Placeholder columns for future epics: abs_server_id, abs_item_id (ABS integration),
-- linked_book_id (series linking), series/series_sequence (series tracking),
-- playback_speed (audio playback). Present now to avoid ALTER TABLE later.
CREATE TABLE IF NOT EXISTS public.books (
  id               UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id          UUID         NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  title            TEXT         NOT NULL,
  author           TEXT,
  narrator         TEXT,
  format           TEXT         NOT NULL DEFAULT 'epub',
  status           TEXT         NOT NULL DEFAULT 'unread'
                     CHECK (status IN ('unread', 'reading', 'finished', 'abandoned')),
  cover_url        TEXT,
  description      TEXT,
  genre            TEXT,
  tags             TEXT[]       NOT NULL DEFAULT '{}',
  chapters         JSONB        NOT NULL DEFAULT '[]',
  source_type      TEXT         NOT NULL
                     CHECK (source_type IN ('local', 'remote', 'opds', 'abs')),
  source_url       TEXT,
  current_position JSONB,
  total_pages      INT,
  total_duration   FLOAT,
  progress         REAL         NOT NULL DEFAULT 0
                     CHECK (progress BETWEEN 0 AND 100),
  isbn             TEXT,
  asin             TEXT,
  rating           FLOAT,
  last_opened_at   TIMESTAMPTZ,
  finished_at      TIMESTAMPTZ,
  file_size        BIGINT,
  abs_server_id    TEXT,
  abs_item_id      TEXT,
  linked_book_id   TEXT,
  series           TEXT,
  series_sequence  TEXT,
  playback_speed   FLOAT,
  created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- Incremental download cursor for E92-S06.
CREATE INDEX IF NOT EXISTS idx_books_user_updated
  ON public.books (user_id, updated_at);

ALTER TABLE public.books ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "users_own_data" ON public.books;
CREATE POLICY "users_own_data"
  ON public.books
  FOR ALL
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP TRIGGER IF EXISTS books_set_updated_at ON public.books;
CREATE TRIGGER books_set_updated_at
  BEFORE UPDATE ON public.books
  FOR EACH ROW EXECUTE FUNCTION extensions.moddatetime('updated_at');


-- ─── Unit 6: upsert_book_progress() ─────────────────────────────────────────
-- SECURITY DEFINER function enforcing monotonic progress upgrades (GREATEST).
-- UPDATE-only: book row must pre-exist via syncableWrite LWW. If the book is not
-- found, raises P0002 (no_data_found) — callers should ensure the row exists first.
-- Status derivation (server-side only, when progress advances):
--   progress >= 100 → 'finished'
--   progress > 0 AND current status is 'unread' → 'reading'
--   otherwise → status unchanged (never regresses)
-- Timestamp clamp: LEAST(p_updated_at, now() + interval '5 minutes') prevents
-- far-future client timestamps from pinning the incremental sync cursor permanently.
-- IS DISTINCT FROM auth guard: handles NULL auth.uid() correctly; != would evaluate
-- to NULL (not TRUE) when auth.uid() is NULL, silently allowing unauthenticated calls.
-- Ownership guard: WHERE id = p_book_id AND user_id = p_user_id prevents cross-user
-- writes even in SECURITY DEFINER context.
-- REVOKE FROM PUBLIC + GRANT TO authenticated: Supabase grants anon by default — must revoke.
CREATE OR REPLACE FUNCTION public.upsert_book_progress(
  p_user_id    UUID,
  p_book_id    UUID,
  p_progress   REAL,
  p_updated_at TIMESTAMPTZ
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_clamped_at TIMESTAMPTZ := LEAST(p_updated_at, now() + interval '5 minutes');
BEGIN
  IF p_user_id IS DISTINCT FROM auth.uid() THEN
    RAISE EXCEPTION 'forbidden: p_user_id does not match authenticated user'
      USING ERRCODE = '42501';
  END IF;

  UPDATE public.books SET
    progress   = GREATEST(progress, p_progress),
    status     = CASE
                   WHEN GREATEST(progress, p_progress) >= 100 THEN 'finished'
                   WHEN GREATEST(progress, p_progress) > 0 AND status = 'unread' THEN 'reading'
                   ELSE status
                 END,
    updated_at = GREATEST(updated_at, v_clamped_at)
  WHERE id = p_book_id AND user_id = p_user_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'book not found or not owned by caller'
      USING ERRCODE = 'P0002';
  END IF;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.upsert_book_progress(UUID, UUID, REAL, TIMESTAMPTZ)
  FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.upsert_book_progress(UUID, UUID, REAL, TIMESTAMPTZ)
  TO authenticated;

COMMENT ON FUNCTION public.upsert_book_progress(UUID, UUID, REAL, TIMESTAMPTZ) IS
  'Monotonic book progress update: progress only advances (GREATEST), '
  'updated_at GREATEST with 5-minute future clamp to protect sync cursor. '
  'UPDATE-only: book row must pre-exist via syncableWrite LWW (raises P0002 if not found). '
  'Status derived server-side: unread→reading (progress>0), any→finished (progress>=100). '
  'Status never regresses. Ownership enforced by WHERE user_id = p_user_id. '
  'SECURITY DEFINER: authz enforced by entry guard p_user_id IS DISTINCT FROM auth.uid(). '
  'RAISE on authz failure aborts the caller transaction (SQLSTATE 42501).';


COMMIT;
