-- E93-S01: P1 Learning Content — 11 tables + 2 SECURITY DEFINER helper functions.
--
-- This migration adds all P1 learning-content tables to the Supabase schema. It
-- is the prerequisite for all downstream E93 sync wiring stories (S02–S08).
--
-- Timestamp note: filename 20260413 reflects the design date; story was authored
-- 2026-04-18. The earlier timestamp is intentional — it orders immediately after
-- 20260413000001_p0_sync_foundation.sql and before the P0 fixup migrations.
-- Do NOT edit this file post-commit; fixups live in separate migrations.
--
-- Dependency order (FK targets before FK holders):
--   1. notes           2. bookmarks       3. flashcards
--   4. flashcard_reviews (→ flashcards)   5. embeddings (→ notes)
--   6. book_highlights 7. vocabulary_items 8. audio_bookmarks
--   9. audio_clips    10. chat_conversations  11. learner_models
--  12. upsert_vocabulary_mastery() function
--  12b. reset_vocabulary_mastery() function (R3 BLOCKER fix — bypasses GREATEST)
--  13. search_similar_notes() function
--
-- Key non-obvious invariants:
--   - notes.deleted maps to soft_deleted (fieldMap in tableRegistry)
--   - flashcard_reviews is INSERT+SELECT only (append-only event log)
--   - audio_bookmarks has NO updated_at column and NO moddatetime trigger (immutable)
--   - chat_conversations.created_at_epoch is BIGINT (epoch ms), not TIMESTAMPTZ
--   - upsert_vocabulary_mastery uses GREATEST monotonic logic + timestamp clamp
--   - reset_vocabulary_mastery bypasses GREATEST for unconditional masteryLevel=0 reset
--   - search_similar_notes uses plpgsql (not sql) to enable auth guard RAISE
--   - vector extension already installed by P0 migration — NOT re-created here
--
-- Idempotency: all statements use IF NOT EXISTS / CREATE OR REPLACE /
-- DROP POLICY IF EXISTS. Safe to re-run.
-- Rollback: supabase/migrations/rollback/20260413000002_p1_learning_content_rollback.sql

BEGIN;


-- ─── Unit 1: notes ──────────────────────────────────────────────────────────
-- Per-user markdown notes, one doc per lesson/video.
-- Soft-delete pattern: deleted=true in Dexie maps to soft_deleted=true here
-- (fieldMap in tableRegistry). conflict_copy + conflict_source_id support
-- E93-S03 conflict resolution (client-side type extension deferred to E93-S03).
-- Tags and linked_note_ids stored as TEXT[] (client sends JSON array).
CREATE TABLE IF NOT EXISTS public.notes (
  id                 UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id            UUID         NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  course_id          TEXT         NOT NULL,
  video_id           TEXT         NOT NULL,
  content            TEXT         NOT NULL DEFAULT '',
  timestamp_seconds  FLOAT,
  tags               TEXT[]       NOT NULL DEFAULT '{}',
  linked_note_ids    TEXT[]       NOT NULL DEFAULT '{}',
  soft_deleted       BOOLEAN      NOT NULL DEFAULT FALSE,
  deleted_at         TIMESTAMPTZ,
  conflict_copy      BOOLEAN      NOT NULL DEFAULT FALSE,
  conflict_source_id UUID,
  created_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at         TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- Incremental download cursor for E92-S06.
CREATE INDEX IF NOT EXISTS idx_notes_user_updated
  ON public.notes (user_id, updated_at);

ALTER TABLE public.notes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users access own notes" ON public.notes;
CREATE POLICY "Users access own notes"
  ON public.notes
  FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- Auto-update updated_at on every UPDATE (LWW sync tables use server-assigned timestamp).
DROP TRIGGER IF EXISTS set_updated_at ON public.notes;
CREATE TRIGGER set_updated_at
  BEFORE UPDATE ON public.notes
  FOR EACH ROW EXECUTE FUNCTION extensions.moddatetime('updated_at');


-- ─── Unit 2: bookmarks ──────────────────────────────────────────────────────
-- Video/lesson bookmarks. timestamp_seconds avoids SQL keyword collision with
-- the reserved word `timestamp`. lesson_id stored as TEXT (no FK to lessons
-- table — consistent with content_progress.content_id TEXT).
CREATE TABLE IF NOT EXISTS public.bookmarks (
  id                UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id           UUID         NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  course_id         TEXT         NOT NULL,
  lesson_id         TEXT         NOT NULL,
  timestamp_seconds FLOAT        NOT NULL DEFAULT 0,
  label             TEXT         NOT NULL DEFAULT '',
  created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- Incremental download cursor for E92-S06.
CREATE INDEX IF NOT EXISTS idx_bookmarks_user_updated
  ON public.bookmarks (user_id, updated_at);

ALTER TABLE public.bookmarks ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users access own bookmarks" ON public.bookmarks;
CREATE POLICY "Users access own bookmarks"
  ON public.bookmarks
  FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP TRIGGER IF EXISTS set_updated_at ON public.bookmarks;
CREATE TRIGGER set_updated_at
  BEFORE UPDATE ON public.bookmarks
  FOR EACH ROW EXECUTE FUNCTION extensions.moddatetime('updated_at');


-- ─── Unit 3: flashcards ─────────────────────────────────────────────────────
-- FSRS-powered flashcards. All FSRS numeric fields included.
-- due_date: Supabase column name (Dexie field is `due`; E93-S03 fieldMap will
-- add `due → due_date` to tableRegistry to handle this rename).
-- state CHECK (0-3): matches CardState enum (0=New,1=Learning,2=Review,3=Relearning).
CREATE TABLE IF NOT EXISTS public.flashcards (
  id             UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id        UUID         NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  course_id      TEXT         NOT NULL,
  note_id        UUID         REFERENCES public.notes(id) ON DELETE SET NULL,
  source_type    TEXT         CHECK (source_type IN ('course', 'book')),
  source_book_id TEXT,
  source_highlight_id TEXT,
  front          TEXT         NOT NULL DEFAULT '',
  back           TEXT         NOT NULL DEFAULT '',
  stability      FLOAT        NOT NULL DEFAULT 0,
  difficulty     FLOAT        NOT NULL DEFAULT 0,
  reps           INT          NOT NULL DEFAULT 0,
  lapses         INT          NOT NULL DEFAULT 0,
  state          INT          NOT NULL DEFAULT 0 CHECK (state IN (0, 1, 2, 3)),
  elapsed_days   INT          NOT NULL DEFAULT 0,
  scheduled_days INT          NOT NULL DEFAULT 0,
  due_date       TIMESTAMPTZ,
  last_review    TIMESTAMPTZ,
  last_rating    INT,
  created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- Incremental download cursor for E92-S06.
CREATE INDEX IF NOT EXISTS idx_flashcards_user_updated
  ON public.flashcards (user_id, updated_at);

ALTER TABLE public.flashcards ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users access own flashcards" ON public.flashcards;
CREATE POLICY "Users access own flashcards"
  ON public.flashcards
  FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP TRIGGER IF EXISTS set_updated_at ON public.flashcards;
CREATE TRIGGER set_updated_at
  BEFORE UPDATE ON public.flashcards
  FOR EACH ROW EXECUTE FUNCTION extensions.moddatetime('updated_at');


-- ─── Unit 4: flashcard_reviews ──────────────────────────────────────────────
-- Append-only FSRS review event log. Immutable once written.
-- INSERT + SELECT policies only — no UPDATE or DELETE policies.
-- Matches the study_sessions pattern from P0: two separate policies, no FOR ALL.
-- flashcard_id FK ON DELETE CASCADE ensures orphan cleanup when cards are deleted.
-- No updated_at column (append-only), no moddatetime trigger.
-- Note: this table has NO entry in tableRegistry — it is Supabase-only and is
-- written via a dedicated upload path in E93-S04 (FSRS replay mechanism).
CREATE TABLE IF NOT EXISTS public.flashcard_reviews (
  id           UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      UUID         NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  flashcard_id UUID         NOT NULL REFERENCES public.flashcards(id) ON DELETE CASCADE,
  rating       INT          NOT NULL,
  reviewed_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
  created_at   TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- Incremental download cursor (append-only table uses created_at as cursor).
CREATE INDEX IF NOT EXISTS idx_flashcard_reviews_user_created
  ON public.flashcard_reviews (user_id, created_at);

ALTER TABLE public.flashcard_reviews ENABLE ROW LEVEL SECURITY;

-- INSERT-only RLS: two policies, no UPDATE/DELETE policies (immutable event log).
DROP POLICY IF EXISTS "insert_own_flashcard_reviews" ON public.flashcard_reviews;
CREATE POLICY "insert_own_flashcard_reviews"
  ON public.flashcard_reviews
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "select_own_flashcard_reviews" ON public.flashcard_reviews;
CREATE POLICY "select_own_flashcard_reviews"
  ON public.flashcard_reviews
  FOR SELECT
  USING (auth.uid() = user_id);


-- ─── Unit 5: embeddings ─────────────────────────────────────────────────────
-- Note vector embeddings (384-dim, all-MiniLM-L6-v2). Separate id PK (not note_id
-- as PK) to allow future multi-vector-per-note scenarios.
-- HNSW index with cosine distance metric for semantic search (search_similar_notes).
-- note_id FK ON DELETE CASCADE: orphaned embeddings auto-cleaned when note deleted.
CREATE TABLE IF NOT EXISTS public.embeddings (
  id         UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    UUID          NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  note_id    UUID          NOT NULL REFERENCES public.notes(id) ON DELETE CASCADE,
  vector     vector(384)   NOT NULL,
  model      TEXT          NOT NULL DEFAULT 'all-MiniLM-L6-v2',
  created_at TIMESTAMPTZ   NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ   NOT NULL DEFAULT now()
);

-- HNSW index for approximate nearest-neighbour cosine similarity search.
-- m=16, ef_construction=64: balanced default (tune in future migration if needed).
CREATE INDEX IF NOT EXISTS idx_embeddings_vector_hnsw
  ON public.embeddings
  USING hnsw (vector vector_cosine_ops)
  WITH (m = 16, ef_construction = 64);

-- Incremental download cursor for E92-S06.
CREATE INDEX IF NOT EXISTS idx_embeddings_user_updated
  ON public.embeddings (user_id, updated_at);

ALTER TABLE public.embeddings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users access own embeddings" ON public.embeddings;
CREATE POLICY "Users access own embeddings"
  ON public.embeddings
  FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP TRIGGER IF EXISTS set_updated_at ON public.embeddings;
CREATE TRIGGER set_updated_at
  BEFORE UPDATE ON public.embeddings
  FOR EACH ROW EXECUTE FUNCTION extensions.moddatetime('updated_at');


-- ─── Unit 6: book_highlights ────────────────────────────────────────────────
-- EPUB book highlights with optional priority review triage (keep/dismiss).
-- text_context and position stored as JSONB (structured but schema-flexible).
-- flashcard_id nullable, no FK constraint — flashcard may be independently deleted.
CREATE TABLE IF NOT EXISTS public.book_highlights (
  id               UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id          UUID         NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  book_id          TEXT         NOT NULL,
  cfi_range        TEXT,
  text_anchor      TEXT         NOT NULL DEFAULT '',
  text_context     JSONB,
  chapter_href     TEXT,
  note             TEXT,
  color            TEXT         NOT NULL DEFAULT 'yellow',
  flashcard_id     UUID,
  position         JSONB,
  review_rating    TEXT,
  last_reviewed_at TIMESTAMPTZ,
  created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- Incremental download cursor for E92-S06.
CREATE INDEX IF NOT EXISTS idx_book_highlights_user_updated
  ON public.book_highlights (user_id, updated_at);

ALTER TABLE public.book_highlights ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users access own book_highlights" ON public.book_highlights;
CREATE POLICY "Users access own book_highlights"
  ON public.book_highlights
  FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP TRIGGER IF EXISTS set_updated_at ON public.book_highlights;
CREATE TRIGGER set_updated_at
  BEFORE UPDATE ON public.book_highlights
  FOR EACH ROW EXECUTE FUNCTION extensions.moddatetime('updated_at');


-- ─── Unit 7: vocabulary_items ───────────────────────────────────────────────
-- Vocabulary words saved from book reader. mastery_level 0-3 enforced at DB level
-- (CHECK constraint), matching VocabularyItem.masteryLevel: 0|1|2|3 in types.ts.
-- upsert_vocabulary_mastery() (Unit 12) enforces monotonic mastery upgrades.
CREATE TABLE IF NOT EXISTS public.vocabulary_items (
  id               UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id          UUID         NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  book_id          TEXT         NOT NULL,
  word             TEXT         NOT NULL,
  context          TEXT,
  definition       TEXT,
  note             TEXT,
  highlight_id     UUID,
  mastery_level    INT          NOT NULL DEFAULT 0 CHECK (mastery_level BETWEEN 0 AND 3),
  last_reviewed_at TIMESTAMPTZ,
  created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- Incremental download cursor for E92-S06.
CREATE INDEX IF NOT EXISTS idx_vocabulary_items_user_updated
  ON public.vocabulary_items (user_id, updated_at);

ALTER TABLE public.vocabulary_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users access own vocabulary_items" ON public.vocabulary_items;
CREATE POLICY "Users access own vocabulary_items"
  ON public.vocabulary_items
  FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP TRIGGER IF EXISTS set_updated_at ON public.vocabulary_items;
CREATE TRIGGER set_updated_at
  BEFORE UPDATE ON public.vocabulary_items
  FOR EACH ROW EXECUTE FUNCTION extensions.moddatetime('updated_at');


-- ─── Unit 8: audio_bookmarks ────────────────────────────────────────────────
-- Audiobook chapter bookmarks. Immutable event — no updated_at column, no
-- moddatetime trigger. Matches the study_sessions pattern from P0.
-- timestamp_seconds avoids SQL keyword collision with the reserved word `timestamp`.
-- Download cursor uses created_at (append-only, no updated_at available).
CREATE TABLE IF NOT EXISTS public.audio_bookmarks (
  id                UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id           UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  book_id           TEXT        NOT NULL,
  chapter_index     INT         NOT NULL DEFAULT 0,
  timestamp_seconds FLOAT       NOT NULL DEFAULT 0,
  note              TEXT,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
  -- No updated_at column: audio_bookmarks are immutable events (AudioBookmark.createdAt only).
  -- No moddatetime trigger: intentionally omitted — see header comment.
);

-- Incremental download cursor (no updated_at → use created_at as cursor).
CREATE INDEX IF NOT EXISTS idx_audio_bookmarks_user_created
  ON public.audio_bookmarks (user_id, created_at);

ALTER TABLE public.audio_bookmarks ENABLE ROW LEVEL SECURITY;

-- INSERT + SELECT policies only — audio_bookmarks are immutable events (no UPDATE/DELETE).
DROP POLICY IF EXISTS "Users access own audio_bookmarks" ON public.audio_bookmarks;
DROP POLICY IF EXISTS "insert_own_audio_bookmarks" ON public.audio_bookmarks;
DROP POLICY IF EXISTS "select_own_audio_bookmarks" ON public.audio_bookmarks;
CREATE POLICY "insert_own_audio_bookmarks"
  ON public.audio_bookmarks
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "select_own_audio_bookmarks"
  ON public.audio_bookmarks
  FOR SELECT
  USING (auth.uid() = user_id);


-- ─── Unit 9: audio_clips ────────────────────────────────────────────────────
-- Clipped audio ranges within audiobook chapters. Mutable (LWW sync).
-- sort_order supports drag-and-drop reordering. AudioClip has no updatedAt in
-- the TypeScript interface but AC1 specifies updated_at column here; E93-S03
-- will handle the mapping gap (use createdAt as fallback or add updatedAt to type).
CREATE TABLE IF NOT EXISTS public.audio_clips (
  id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  book_id       TEXT        NOT NULL,
  chapter_id    TEXT        NOT NULL,
  chapter_index INT         NOT NULL DEFAULT 0,
  start_time    FLOAT       NOT NULL DEFAULT 0,
  end_time      FLOAT       NOT NULL DEFAULT 0,
  title         TEXT,
  sort_order    INT         NOT NULL DEFAULT 0,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Incremental download cursor for E92-S06.
CREATE INDEX IF NOT EXISTS idx_audio_clips_user_updated
  ON public.audio_clips (user_id, updated_at);

ALTER TABLE public.audio_clips ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users access own audio_clips" ON public.audio_clips;
CREATE POLICY "Users access own audio_clips"
  ON public.audio_clips
  FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP TRIGGER IF EXISTS set_updated_at ON public.audio_clips;
CREATE TRIGGER set_updated_at
  BEFORE UPDATE ON public.audio_clips
  FOR EACH ROW EXECUTE FUNCTION extensions.moddatetime('updated_at');


-- ─── Unit 10: chat_conversations ────────────────────────────────────────────
-- Persisted tutor chat conversations.
-- created_at_epoch: BIGINT storing epoch ms from ChatConversation.createdAt (number).
--   The client sends epoch ms; E93-S03 fieldMap entry `createdAt → created_at_epoch`
--   handles the rename. NOT a TIMESTAMPTZ — raw epoch ms is preserved as-is.
-- updated_at: TIMESTAMPTZ for moddatetime trigger and incremental sync cursor.
--   E93-S03 upload path must convert ChatConversation.updatedAt (epoch ms) to
--   TIMESTAMPTZ before writing to Supabase.
-- messages stored as JSONB (TutorMessage[]).
CREATE TABLE IF NOT EXISTS public.chat_conversations (
  id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id          UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  course_id        TEXT        NOT NULL,
  video_id         TEXT        NOT NULL,
  mode             TEXT        NOT NULL DEFAULT 'tutor',
  hint_level       INT         NOT NULL DEFAULT 0,
  messages         JSONB       NOT NULL DEFAULT '[]',
  created_at_epoch BIGINT      NOT NULL,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Incremental download cursor for E92-S06.
CREATE INDEX IF NOT EXISTS idx_chat_conversations_user_updated
  ON public.chat_conversations (user_id, updated_at);

ALTER TABLE public.chat_conversations ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users access own chat_conversations" ON public.chat_conversations;
CREATE POLICY "Users access own chat_conversations"
  ON public.chat_conversations
  FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- Trigger targets updated_at only — NOT created_at_epoch (which must remain
-- the original epoch ms value as supplied by the client).
DROP TRIGGER IF EXISTS set_updated_at ON public.chat_conversations;
CREATE TRIGGER set_updated_at
  BEFORE UPDATE ON public.chat_conversations
  FOR EACH ROW EXECUTE FUNCTION extensions.moddatetime('updated_at');


-- ─── Unit 11: learner_models ────────────────────────────────────────────────
-- Per-course learner models updated at session boundaries (E72-S01).
-- UNIQUE (user_id, course_id): enforced at DB level; E93-S08 uses ON CONFLICT
-- DO UPDATE for upsert semantics (one model per user per course).
-- strengths, misconceptions, quiz_stats stored as JSONB (ConceptAssessment[]).
-- topics_explored stored as TEXT[].
CREATE TABLE IF NOT EXISTS public.learner_models (
  id                   UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id              UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  course_id            TEXT        NOT NULL,
  vocabulary_level     TEXT        NOT NULL DEFAULT 'beginner',
  strengths            JSONB       NOT NULL DEFAULT '[]',
  misconceptions       JSONB       NOT NULL DEFAULT '[]',
  topics_explored      TEXT[]      NOT NULL DEFAULT '{}',
  preferred_mode       TEXT        NOT NULL DEFAULT 'tutor',
  last_session_summary TEXT        NOT NULL DEFAULT '',
  quiz_stats           JSONB       NOT NULL DEFAULT '{"totalQuestions":0,"correctAnswers":0,"weakTopics":[]}',
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT learner_models_user_course_unique UNIQUE (user_id, course_id)
);

-- Incremental download cursor for E92-S06.
CREATE INDEX IF NOT EXISTS idx_learner_models_user_updated
  ON public.learner_models (user_id, updated_at);

ALTER TABLE public.learner_models ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users access own learner_models" ON public.learner_models;
CREATE POLICY "Users access own learner_models"
  ON public.learner_models
  FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP TRIGGER IF EXISTS set_updated_at ON public.learner_models;
CREATE TRIGGER set_updated_at
  BEFORE UPDATE ON public.learner_models
  FOR EACH ROW EXECUTE FUNCTION extensions.moddatetime('updated_at');


-- ─── Unit 12: upsert_vocabulary_mastery() ───────────────────────────────────
-- SECURITY DEFINER function enforcing monotonic mastery upgrades (GREATEST).
-- Required because vocabulary_items uses FOR ALL RLS — SECURITY INVOKER would
-- fail under certain JWT edge cases with ON CONFLICT DO UPDATE. Entry guard
-- replaces RLS auth.uid() = user_id check with an explicit IS DISTINCT FROM
-- (handles NULL auth.uid() correctly; `!=` would evaluate to NULL, not TRUE).
-- Timestamp clamp: LEAST(p_updated_at, now() + interval '5 minutes') prevents
-- far-future client timestamps from pinning the incremental sync cursor permanently.
-- SQLSTATE 42501 (insufficient_privilege) is semantically correct for authz failure.
-- p_book_id and p_word are NOT NULL in vocabulary_items — required on INSERT.
-- p_context, p_definition, p_note, p_highlight_id are nullable and default to NULL;
-- excluded from ON CONFLICT DO UPDATE (immutable once set).
-- p_last_reviewed_at is nullable and included in ON CONFLICT DO UPDATE (mutable).
CREATE OR REPLACE FUNCTION public.upsert_vocabulary_mastery(
  p_user_id            UUID,
  p_vocabulary_item_id UUID,
  p_book_id            TEXT,
  p_word               TEXT,
  p_mastery_level      INT,
  p_updated_at         TIMESTAMPTZ,
  p_context            TEXT        DEFAULT NULL,
  p_definition         TEXT        DEFAULT NULL,
  p_note               TEXT        DEFAULT NULL,
  p_highlight_id       UUID        DEFAULT NULL,
  p_last_reviewed_at   TIMESTAMPTZ DEFAULT NULL
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_clamped TIMESTAMPTZ := LEAST(p_updated_at, now() + interval '5 minutes');
BEGIN
  IF p_user_id IS DISTINCT FROM auth.uid() THEN
    RAISE EXCEPTION 'forbidden: p_user_id does not match authenticated user'
      USING ERRCODE = '42501';
  END IF;

  INSERT INTO public.vocabulary_items (
    id, user_id, book_id, word,
    context, definition, note, highlight_id, last_reviewed_at,
    mastery_level, updated_at
  )
  VALUES (
    p_vocabulary_item_id, p_user_id, p_book_id, p_word,
    p_context, p_definition, p_note, p_highlight_id, p_last_reviewed_at,
    p_mastery_level, v_clamped
  )
  ON CONFLICT (id) DO UPDATE SET
    mastery_level    = GREATEST(vocabulary_items.mastery_level, EXCLUDED.mastery_level),
    last_reviewed_at = COALESCE(EXCLUDED.last_reviewed_at, vocabulary_items.last_reviewed_at),
    updated_at       = GREATEST(vocabulary_items.updated_at, v_clamped);
  -- book_id and word are intentionally excluded from DO UPDATE (immutable once set).
END;
$$;

REVOKE EXECUTE ON FUNCTION public.upsert_vocabulary_mastery(UUID, UUID, TEXT, TEXT, INT, TIMESTAMPTZ, TEXT, TEXT, TEXT, UUID, TIMESTAMPTZ)
  FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.upsert_vocabulary_mastery(UUID, UUID, TEXT, TEXT, INT, TIMESTAMPTZ, TEXT, TEXT, TEXT, UUID, TIMESTAMPTZ)
  TO authenticated;

COMMENT ON FUNCTION public.upsert_vocabulary_mastery(UUID, UUID, TEXT, TEXT, INT, TIMESTAMPTZ, TEXT, TEXT, TEXT, UUID, TIMESTAMPTZ) IS
  'Monotonic vocabulary mastery upsert: mastery_level only advances (GREATEST), '
  'updated_at GREATEST with 5-minute future clamp to protect sync cursor. '
  'p_book_id and p_word are required (NOT NULL columns); nullable fields default to NULL. '
  'book_id and word excluded from ON CONFLICT DO UPDATE (immutable once set). '
  'SECURITY DEFINER: authz enforced by entry guard p_user_id IS DISTINCT FROM auth.uid(). '
  'RAISE on authz failure aborts the caller transaction (SQLSTATE 42501).';


-- ─── Unit 12b: reset_vocabulary_mastery() ──────────────────────────────────
-- SECURITY DEFINER function for unconditional mastery reset (masteryLevel → 0).
-- Required because upsert_vocabulary_mastery uses GREATEST monotonic logic which
-- silently ignores reset calls (masteryLevel=0) when the server value is higher,
-- causing permanent Dexie/Supabase divergence (R3 BLOCKER fix).
-- p_updated_at is applied directly (no GREATEST clamp) — the caller controls the
-- reset timestamp. A 5-minute future clamp still prevents clock-skew abuse.
-- auth guard uses IS DISTINCT FROM (handles NULL auth.uid() correctly).
CREATE OR REPLACE FUNCTION public.reset_vocabulary_mastery(
  p_id          UUID,
  p_user_id     UUID,
  p_updated_at  TIMESTAMPTZ
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_clamped TIMESTAMPTZ := LEAST(p_updated_at, now() + interval '5 minutes');
BEGIN
  IF auth.uid() IS DISTINCT FROM p_user_id THEN
    RAISE EXCEPTION 'forbidden: p_user_id does not match authenticated user'
      USING ERRCODE = '42501';
  END IF;
  UPDATE public.vocabulary_items
  SET mastery_level    = 0,
      last_reviewed_at = NULL,
      updated_at       = v_clamped
  WHERE id = p_id AND user_id = p_user_id;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.reset_vocabulary_mastery(UUID, UUID, TIMESTAMPTZ)
  FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.reset_vocabulary_mastery(UUID, UUID, TIMESTAMPTZ)
  TO authenticated;

COMMENT ON FUNCTION public.reset_vocabulary_mastery(UUID, UUID, TIMESTAMPTZ) IS
  'Unconditional vocabulary mastery reset to 0. Bypasses the GREATEST monotonic '
  'guard in upsert_vocabulary_mastery so that resetMastery calls always take effect '
  'on the server, preventing Dexie/Supabase divergence. '
  'SECURITY DEFINER: authz enforced by entry guard auth.uid() IS DISTINCT FROM p_user_id. '
  'RAISE on authz failure aborts the caller transaction (SQLSTATE 42501).';


-- ─── Unit 13: search_similar_notes() ────────────────────────────────────────
-- SECURITY DEFINER function for cosine-similarity note search via pgvector.
-- Uses plpgsql (not sql) to enable auth guard RAISE — pure sql functions cannot
-- RAISE, so a plpgsql wrapper is required for the IS DISTINCT FROM auth check.
-- Filters soft-deleted notes. Orders by cosine distance ascending (closest first).
-- p_limit defaults to 10; callers may pass a smaller value for tighter result sets.
CREATE OR REPLACE FUNCTION public.search_similar_notes(
  p_user_id     UUID,
  p_query_vector vector(384),
  p_limit       INT DEFAULT 10
)
RETURNS TABLE(note_id UUID, distance FLOAT)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  IF p_user_id IS DISTINCT FROM auth.uid() THEN
    RAISE EXCEPTION 'forbidden: p_user_id does not match authenticated user'
      USING ERRCODE = '42501';
  END IF;

  RETURN QUERY
  SELECT e.note_id,
         (e.vector <=> p_query_vector)::FLOAT AS distance
  FROM   public.embeddings e
  JOIN   public.notes n ON n.id = e.note_id
  WHERE  e.user_id = p_user_id
    AND  n.soft_deleted IS NOT TRUE
  ORDER  BY e.vector <=> p_query_vector ASC
  LIMIT  p_limit;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.search_similar_notes(UUID, vector(384), INT)
  FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.search_similar_notes(UUID, vector(384), INT)
  TO authenticated;

COMMENT ON FUNCTION public.search_similar_notes(UUID, vector(384), INT) IS
  'Cosine-similarity search over note embeddings. Excludes soft-deleted notes. '
  'Returns (note_id, distance) ordered by distance ASC (closest first). '
  'SECURITY DEFINER: authz enforced by entry guard p_user_id IS DISTINCT FROM auth.uid(). '
  'RAISE on authz failure aborts the caller transaction (SQLSTATE 42501).';


COMMIT;
